	//  Interfaz de envío principal de [!output CLASS_NAME_ROOT]
		
	[ uuid([!output DISPIID_REGISTRY_FORMAT]) ]
	dispinterface I[!output CLASS_NAME_ROOT]
	{
		properties:
		methods:
	};

	//  Información de clase de [!output CLASS_NAME_ROOT]

	[ uuid([!output CLSID_REGISTRY_FORMAT]) ]
	coclass [!output CLASS_NAME_ROOT]
	{
		[default] dispinterface I[!output CLASS_NAME_ROOT];
	};
