	//  Interface de dispatch principale pour [!output CLASS_NAME_ROOT]
		
	[ uuid([!output DISPIID_REGISTRY_FORMAT]) ]
	dispinterface I[!output CLASS_NAME_ROOT]
	{
		properties:
		methods:
	};

	//  Informations de classe pour [!output CLASS_NAME_ROOT]

	[ uuid([!output CLSID_REGISTRY_FORMAT]) ]
	coclass [!output CLASS_NAME_ROOT]
	{
		[default] dispinterface I[!output CLASS_NAME_ROOT];
	};
