#pragma once

using namespace ATL;

template <class T>
class CProxy_[!output INTERFACE_NAME]Events : public IConnectionPointImpl<T, &__uuidof( _[!output INTERFACE_NAME]Events ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
