//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $rootnamespace$
{
    public partial class Default
    {

        /// <summary>
        /// form1 $loc_ControlComment$.
        /// </summary>
        /// <remarks>
        /// $loc_AutoGenComment$
        /// $loc_ModifyComment$
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
